const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS' ,
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    
    CREATE_ERRORS: 'CREATE_ERRORS',
    SET_LOADER: 'SET_LOADER',
    CLOSE_LOADER: 'CLOSE_LOADER'
}

export default ACTIONS